name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:[This is the system response] Hello! Welcome to here! You can go to # 22 to view the details of this repository. If you have already viewed or understood us, please ignore this item. Thank you!
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Message that will be displayed on users' first issue"
        pr-message: "Message that will be displayed on users' first pull request"
